# Generated by Django 4.0.6 on 2022-08-01 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='navn på arrangør')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='navn på arrangement')),
                ('category', models.CharField(choices=[('RP', 'Rollespill'), ('BG', 'Brettspill'), ('NA', 'Annet')], max_length=2)),
                ('start_time', models.DateTimeField(verbose_name='starttidspunkt')),
                ('end_time', models.DateTimeField(verbose_name='slutttidspunkt')),
                ('max_players', models.IntegerField(default=0, verbose_name='maks antall spillere')),
                ('location', models.CharField(blank=True, max_length=30, verbose_name='plassering')),
                ('description', models.TextField(blank=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.organizer')),
            ],
        ),
    ]
