# Generated by Django 4.1 on 2022-08-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time'], 'verbose_name': 'arrangement', 'verbose_name_plural': 'arrangementer'},
        ),
        migrations.AlterModelOptions(
            name='organizer',
            options={'verbose_name': 'kontaktperson', 'verbose_name_plural': 'kontaktpersoner'},
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.organizer', verbose_name='kontaktperson'),
        ),
    ]
